
name: Deploy to Oracle Cloud Ubuntu Server

on:
  push:
    branches:
      - master # Trigger deployment on push to the main branch

jobs:
  deploy:
    name: Deploy to Oracle Cloud Server
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_ORACLE }}

    # Step 3: Deploy to Oracle Cloud Server
    - name: Deploy to Oracle Cloud Server
      env:
        NODE_ENV: production
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.ORACLE_SERVER_IP }} << 'EOF'
          # Navigate to the project directory
          cd /home/ubuntu/apps/doctor-appointment-app

          # Pull the latest changes from the main branch
          git pull origin master

          # Build the Docker image
          docker-compose build

          # Restart the Docker Compose services
          docker-compose down
          docker-compose up -d
        EOF